package integration_tests

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"time"

	"github.com/gruntwork-io/terratest/modules/k8s"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	testHelpers "github.com/ministryofjustice/cloud-platform-infrastructure/test/helpers"
)

var _ = Describe("Kube State Metrics", func() {
	var tunnel *k8s.Tunnel

	BeforeEach(func() {
		options := k8s.NewKubectlOptions("", "", "monitoring")
		tunnel = k8s.NewTunnel(options, k8s.ResourceTypeService, "prometheus-operated", 0, 9090)
		tunnel.ForwardPort(GinkgoT())
	})

	AfterEach(func() {
		tunnel.Close()
	})

	// "up" is generated by Prometheus per scrape — 1 = healthy, 0 = scrape failed, absent = stale.
	It("should return the kube-state-metrics up status as 1", func() {
		prometheusURL := fmt.Sprintf("http://%s", tunnel.Endpoint())
		GinkgoWriter.Println("Prometheus URL:", prometheusURL)

		query := url.Values{"query": {`up{job="kube-state-metrics"}`}}
		var result testHelpers.PrometheusResponse

		client := &http.Client{Timeout: 30 * time.Second}
		Eventually(func() bool {
			resp, err := client.Get(prometheusURL + "/api/v1/query?" + query.Encode())
			if err != nil {
				return false
			}
			defer resp.Body.Close()

			if resp.StatusCode != http.StatusOK {
				return false
			}
			if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
				return false
			}

			return result.Status == "success" && len(result.Data.Result) > 0
		}).WithTimeout(5*time.Minute).WithPolling(30*time.Second).Should(BeTrue(), "no successful 'up' series found for job=kube-state-metrics — KSM may be down or not scraped yet")

		Expect(result.Data.Result[0].Value[1]).To(Equal("1"), "kube-state-metrics scrape is unhealthy (up=0); check the KSM pod in the monitoring namespace")
	})
})
