# Default values for oidc-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: evry/oidc-proxy
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# OIDC service
service:
  type: ClusterIP
  port: 80

# Application
application:
  serviceName: ""
  port: ""
  hostName: kuberos.cluster.local
  healthCheck:
    enabled: false
    path: ""

resources:
  limits:
    cpu: 5m
    memory: 64Mi
  requests:
    cpu: 5m
    memory: 64Mi

# OIDC prvider
oidc:
  clientId: ""
  clientSecret: ""
  discovery: ""
  renewToken: ""
  sessionName: ""
  sessionSecret: ""
