apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name:
spec:
  api:
    loadBalancer:
      type: Public
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "route53:ChangeResourceRecordSets"
          ],
          "Resource": [
            "arn:aws:route53:::hostedzone/Z178U6OM3IG0YL"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "route53:ListHostedZones",
            "route53:ListResourceRecordSets"
          ],
          "Resource": [
            "*"
          ]
        }
      ]
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: 
  dnsZone: 
  etcdClusters:
  - etcdMembers:
    - instanceGroup: 
      name:
    - instanceGroup:
      name:
    - instanceGroup:
      name:
    name: main
  - etcdMembers:
    - instanceGroup:
      name:
    - instanceGroup:
      name:
    - instanceGroup:
      name:
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    oidcClientID: 0NKzhJ2SRKydz3XKRseVpvO7gA1D7VxY
    oidcIssuerURL: https://moj-cloud-platforms-dev.eu.auth0.com/
    oidcUsernameClaim: nickname
    oidcGroupsClaim: https://k8s.integration.dsd.io/groups
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.8.6
  masterPublicName:
  networkCIDR:
  networking:
    calico: {}
  nonMasqueradeCIDR:
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 
    name: 
    type: 
    zone: 
  - cidr: 
    name: 
    type: 
    zone: 
  - cidr: 
    name: 
    type: 
    zone: 
  - cidr: 
    name: 
    type: 
    zone: 
  - cidr: 
    name: 
    type: 
    zone: 
  - cidr: 
    name: 
    type: 
    zone: 
  topology:
    bastion:
      bastionPublicName: 
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: 
  name:
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: master
  role: Master
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster:
  name: nodes
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-1a
  - eu-west-1b
  - eu-west-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: 
  name: bastions
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-01-14
  machineType: t2.micro
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: bastions
  role: Bastion
  subnets:
  - utility-eu-west-1a
  - utility-eu-west-1b
  - utility-eu-west-1c
