apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-expand
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
reclaimPolicy: Delete
allowVolumeExpansion: true
