apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc-proxy.secretName" . }}
  labels:
    app.kubernetes.io/name: {{ include "oidc-proxy.name" . }}
    helm.sh/chart: {{ include "oidc-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  clientSecret: {{ .Values.oidc.clientSecret | b64enc | quote }}
  sessionSecret: {{ .Values.oidc.sessionSecret | b64enc | quote }}

