AWSTemplateFormatVersion: '2010-09-09'
Description: Create the baseline IAM Instance Roles and Profiles for the AWS account
Metadata:
  Stack:
    Value: '1'
  VersionDate:
    Value: '20160510'
  Identifier:
    Value: template-iam
  Input:
    Description: Creates Instance Roles and Profiles
  Output:
    Description: Outputs ID of all deployed resources
Resources:
  rSysAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: rSysAdminRole-inst
  rSysAdminProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: rSysAdminRole
    Properties:
      Path: /
      Roles:
        - !Ref 'rSysAdminRole'
      InstanceProfileName: rSysAdminProfile-inst
  rSysAdminPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            NotAction: iam:*
            Resource: '*'
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
          - Effect: Deny
            Action: aws-portal:*Billing
            Resource: '*'
          - Effect: Deny
            Action:
              - cloudtrail:DeleteTrail
              - cloudtrail:StopLogging
              - cloudtrail:UpdateTrail
            Resource: '*'
          - Effect: Deny
            Action:
              - kms:Create*
              - kms:Revoke*
              - kms:Enable*
              - kms:Get*
              - kms:Disable*
              - kms:Delete*
              - kms:Put*
              - kms:Update*
            Resource: '*'
      Roles:
        - !Ref rSysAdminRole
      ManagedPolicyName: rSysAdminPolicy-inst
  rIAMAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: rIAMAdminRole-inst
  rIAMAdminProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: rIAMAdminRole
    Properties:
      Path: /
      Roles:
        - !Ref rIAMAdminRole
      InstanceProfileName: rIAMAdminProfile-inst
  rIAMAdminPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: iam:*
            Resource: '*'
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
          - Effect: Deny
            Action: aws-portal:*Billing
            Resource: '*'
      Roles:
        - !Ref rIAMAdminRole
      ManagedPolicyName: rIAMAdminPolicy-inst
  rInstanceOpsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: rInstanceOpsRole-inst
  rInstanceOpsProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: rIAMAdminRole
    Properties:
      Path: /
      Roles:
        - !Ref rIAMAdminRole
      InstanceProfileName: rInstanceOpsProfile-inst
  rInstanceOpsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: ec2:*
            Effect: Allow
            Resource: '*'
          - Effect: Allow
            Action: elasticloadbalancing:*
            Resource: '*'
          - Effect: Allow
            Action: cloudwatch:*
            Resource: '*'
          - Effect: Allow
            Action: autoscaling:*
            Resource: '*'
          - Effect: Deny
            Action:
              - ec2:CreateVpc*
              - ec2:DeleteVpc*
              - ec2:ModifyVpc*
              - ec2:CreateSubnet*
              - ec2:DeleteSubnet*
              - ec2:ModifySubnet*
              - ec2:Create*Route*
              - ec2:DeleteRoute*
              - ec2:AssociateRoute*
              - ec2:ReplaceRoute*
              - ec2:CreateVpn*
              - ec2:DeleteVpn*
              - ec2:AttachVpn*
              - ec2:DetachVpn*
              - ec2:CreateNetworkAcl*
              - ec2:DeleteNetworkAcl*
              - ec2:ReplaceNetworkAcl*
              - ec2:*Gateway*
              - ec2:*PeeringConnection*
            Resource: '*'
          - Effect: Deny
            Action: aws-portal:*Billing
            Resource: '*'
          - Effect: Deny
            Action:
              - kms:Create*
              - kms:Revoke*
              - kms:Enable*
              - kms:Get*
              - kms:Disable*
              - kms:Delete*
              - kms:Put*
              - kms:Update*
            Resource: '*'
      Roles:
        - !Ref rInstanceOpsRole
      ManagedPolicyName: rInstanceOpsPolicy-inst
  rReadOnlyAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      RoleName: rReadOnlyAdminRole-inst
  rReadOnlyAdminProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: rReadOnlyAdminRole
    Properties:
      Path: /
      Roles:
        - !Ref rReadOnlyAdminRole
      InstanceProfileName: rReadOnlyAdminProfile-inst
  rReadOnlyAdminPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn: rReadOnlyAdminProfile
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - appstream:Get*
              - autoscaling:Describe*
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResource
              - cloudformation:DescribeStackResources
              - cloudformation:GetTemplate
              - cloudformation:List*
              - cloudfront:Get*
              - cloudfront:List*
              - cloudtrail:DescribeTrails
              - cloudtrail:GetTrailStatus
              - cloudwatch:Describe*
              - cloudwatch:Get*
              - cloudwatch:List*
              - directconnect:Describe*
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:DescribeTable
              - dynamodb:ListTables
              - ec2:Describe*
              - elasticache:Describe*
              - elasticbeanstalk:Check*
              - elasticbeanstalk:Describe*
              - elasticbeanstalk:List*
              - elasticbeanstalk:RequestEnvironmentInfo
              - elasticbeanstalk:RetrieveEnvironmentInfo
              - elasticloadbalancing:Describe*
              - elastictranscoder:Read*
              - elastictranscoder:List*
              - iam:List*
              - iam:Get*
              - kinesis:Describe*
              - kinesis:Get*
              - kinesis:List*
              - opsworks:Describe*
              - opsworks:Get*
              - route53:Get*
              - route53:List*
              - redshift:Describe*
              - redshift:ViewQueriesInConsole
              - rds:Describe*
              - rds:ListTagsForResource
              - s3:Get*
              - s3:List*
              - sdb:GetAttributes
              - sdb:List*
              - sdb:Select*
              - ses:Get*
              - ses:List*
              - sns:Get*
              - sns:List*
              - sqs:GetQueueAttributes
              - sqs:ListQueues
              - sqs:ReceiveMessage
              - storagegateway:List*
              - storagegateway:Describe*
              - trustedadvisor:Describe*
            Effect: Allow
            Resource: '*'
          - Effect: Deny
            Action: aws-portal:*Billing
            Resource: '*'
      Roles:
        - !Ref rReadOnlyAdminRole
      ManagedPolicyName: rReadOnlyAdminPolicy-inst
  rReadOnlyBillingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: aws-portal:View*
            Resource: '*'
          - Effect: Deny
            Action: aws-portal:*Account
            Resource: '*'
      ManagedPolicyName: rReadOnlyBillingPolicy-inst
Outputs:
  rSysAdminRole:
    Value: !Ref rSysAdminRole
  rIAMAdminRole:
    Value: !Ref rIAMAdminRole
  rInstanceOpsRole:
    Value: !Ref rInstanceOpsRole
  rReadOnlyBillingPolicy:
    Value: !Ref rReadOnlyBillingPolicy
  rReadOnlyAdminRole:
    Value: !Ref rReadOnlyAdminRole
