AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template creates the standard IAM Security Groups - IAMAdminGroup,
  BillingAdminGroup,InfraAdminGroup, NetworkAdminGroup, UserDeveloperGroup, UserLiveSupportGroup and AuditAdminGroup
  to reflect cross-account roles in other accounts'

Parameters: {}

Resources:

  IAMAdminPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: IAMAdminPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/IAMAdminRole
      Groups:
      - !Ref IAMAdminGroup
  IAMAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: IAMAdminGroup

  BillingAdminPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: BillingAdminPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/BillingAdminRole
      Groups:
      - !Ref BillingAdminGroup
  BillingAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: BillingAdminGroup

  InfraAdminPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: InfraAdminPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/InfraAdminRole
      Groups:
      - !Ref InfraAdminGroup
  InfraAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: InfraAdminGroup

  NetworkAdminPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: NetworkAdminPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/NetworkAdminRole
      Groups:
      - !Ref NetworkAdminGroup
  NetworkAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: NetworkAdminGroup

  UserDeveloperPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: UserDeveloperPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/UserDeveloperRole
      Groups:
      - !Ref UserDeveloperGroup
  UserDeveloperGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: UserDeveloperGroup

  UserDBAPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: UserDBAPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/UserDBARole
      Groups:
      - !Ref UserDBAGroup
  UserDBAGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: UserDBAGroup

  UserTesterPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: UserTesterPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/UserTesterRole
      Groups:
      - !Ref UserTesterGroup
  UserTesterGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: UserTesterGroup

  AuditAdminPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: AuditAdminPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/AuditAdminRole
      Groups:
      - !Ref AuditAdminGroup
  AuditAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AuditAdminGroup

  UserLiveSupportPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: UserLiveSupportPolicy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action: "sts:AssumeRole"
          Resource:
          - arn:aws:iam::*:role/UserLiveSupportRole
      Groups:
      - !Ref UserLiveSupportGroup
  UserLiveSupportGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: UserLiveSupportGroup
