kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mps-dev-admins
  namespace: mps-dev
subjects:
  - kind: Group
    name: "github:moving-people-safely"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io