kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pvbpublic-dev-admins
  namespace: pvbpublic-dev
subjects:
  - kind: Group
    name: "github:prison-visits-booking"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
