---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: docker-registry-cache
spec:
  hard:
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: docker-registry-cache
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1000Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi
    type: Container
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: docker-registry-cache-admin
  namespace: docker-registry-cache
subjects:
  - kind: Group
    name: "github:webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
