---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{  template "fluentd-es.fullname" . }}
  labels:
    k8s-app: fluentd-es
    version: {{ .Values.image.tag }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-es
      version: {{ .Values.image.tag }}
  template:
    metadata:
      labels:
        k8s-app: fluentd-es
        kubernetes.io/cluster-service: "true"
        version: {{ .Values.image.tag }}
        app: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
      # This annotation ensures that fluentd does not get evicted if the node
      # supports critical pod annotation based priority scheme.
      # Note that this does not guarantee admission on the nodes (#40573).
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      priorityClassName: node-critical
      serviceAccountName: {{ .Release.Name }}
      tolerations:
      # This needs to run on all nodes, including masters.
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: {{  template "fluentd-es.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        - name:  FLUENT_ELASTICSEARCH_HOST
          value: {{ .Values.fluent_elasticsearch_host }}
        - name:  FLUENT_ELASTICSEARCH_AUDIT_HOST
          value: {{ .Values.fluent_elasticsearch_audit_host }}
        - name: FLUENT_KUBERNETES_CLUSTER_NAME
          value: {{ .Values.fluent_kubernetes_cluster_name }}
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 10m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: {{  template "fluentd-es.fullname" . }}-config
