# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rspec"
gem "pry-byebug"
gem "aws-sdk-core", "~> 3.59"
gem "aws-sdk-iam", "~> 1.3"
gem "aws-sdk-route53", "~> 1.27"
