version: 0.2

env:
  variables:
     region: "eu-west-1"
     domain: "k8s.kops.integration.dsd.io"
     kops_version: "1.8.0"
     helm_version: "2.8.2"
     terraform_version: "0.11.5"
     workspace: "test-cluster"

phases:
  install:
    commands:
       - apt update
       - apt install -y awscli git unzip openssh-client
       - wget https://github.com/kubernetes/kops/releases/download/"$kops_version"/kops-linux-amd64
       - chmod +x kops-linux-amd64 && mv kops-linux-amd64 /usr/local/bin/kops
       - url="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
       - curl -LO https://storage.googleapis.com/kubernetes-release/release/$url/bin/linux/amd64/kubectl
       - chmod +x kubectl && mv ./kubectl /usr/local/bin/kubectl
       - wget https://storage.googleapis.com/kubernetes-helm/helm-v"$helm_version"-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz
       - chmod +x ./linux-amd64/helm && mv ./linux-amd64/helm /usr/local/bin/helm
       - wget https://releases.hashicorp.com/terraform/$terraform_version/terraform_"$terraform_version"_linux_amd64.zip -O terraform.zip
       - unzip terraform.zip -d /usr/local/bin/; chmod +x /usr/local/bin/terraform

  pre_build:
    commands:
      - chmod +x bin/*
      - cd /terraform/cloud-platform

  build:
    commands:
# todo for each
      - terraform init
      - terraform workspace new "$workspace"
      - terraform plan -out plan.out
      - terraform show plan.out
      - terraform apply plan.out

      - mkdir "~/keys"
      - mkdir "~/.ssh/" && chmod 700 "~/.ssh/"
      - ssh-keygen -t rsa -b 4096 -N '' -C "kubernetes-admin" -f "~/keys/kubernetes-admin"
      - mv "~/keys/kubernetes-admin" "~/.ssh/kubernetes-admin" && chmod 600 "~/.ssh/kubernetes-admin"

      - python ../../bin/create_cluster.py ../../kops/"$workspace".yaml > clusterspec.yaml
      - kops cluster create -f clusterspec.yaml
      - aws s3 cp clusterspec.yaml s3://`terraform output kops_state_store`/`terraform output cluster_domain_name`

      - kubectl cluster-info
      - echo 'Done.'

#  post_build:
#    commands:
#       - ""
