version: 0.2

env:
  variables:
     kops_version: "1.8.0"
     helm_version: "2.8.2"
     terraform_version: "0.11.5"

phases:
  install:
    commands:
       - apt update
       - apt install -y awscli git unzip openssh-client
       - wget https://github.com/kubernetes/kops/releases/download/"$kops_version"/kops-linux-amd64
       - chmod +x kops-linux-amd64 && mv kops-linux-amd64 /usr/local/bin/kops
       - url="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
       - curl -LO https://storage.googleapis.com/kubernetes-release/release/$url/bin/linux/amd64/kubectl
       - chmod +x kubectl && mv ./kubectl /usr/local/bin/kubectl
       - wget https://storage.googleapis.com/kubernetes-helm/helm-v"$helm_version"-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz
       - chmod +x ./linux-amd64/helm && mv ./linux-amd64/helm /usr/local/bin/helm
       - wget https://releases.hashicorp.com/terraform/$terraform_version/terraform_"$terraform_version"_linux_amd64.zip -O terraform.zip
       - unzip terraform.zip -d /usr/local/bin/; chmod +x /usr/local/bin/terraform

  pre_build:
    commands:
      - chmod +x bin/*
      - cd terraform/cloud-platform

  build:
    commands:
      - python ../../bin/99-multiple_clusters.py
      - echo 'Done.'
