apiVersion: v1
kind: Pod
metadata:
  annotations:
    vpc.amazonaws.com/pod-ips: 172.20.168.16
  creationTimestamp: "2025-10-17T11:50:00Z"
  generateName: coredns-6c5547977-
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
    pod-template-hash: 6c5547977
  name: coredns-6c5547977-4mm5h
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-6c5547977
    uid: b0a2b9cc-0e67-4d44-9a17-f799283fd0b7
  resourceVersion: "1310"
  uid: ba137034-ed43-4b2b-90bb-245e43ec9fc9
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - arm64
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - kube-dns
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/coredns:v1.11.4-eksbuild.14
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-j2vcs
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: ip-172-20-175-120.eu-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        k8s-app: kube-dns
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: kube-api-access-j2vcs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-10-17T11:51:07Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-17T11:51:06Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-10-17T11:51:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-10-17T11:51:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-17T11:51:06Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://38a8c86cc1080be3d4fa1f631285ade0de07ce8f05b8477390d94fa58012591f
    image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/coredns:v1.11.4-eksbuild.14
    imageID: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/coredns@sha256:d0b6289af4cc69e8190d037a4263ae30dec79011f4d1dd4edb5b7d5bf233073c
    lastState: {}
    name: coredns
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-10-17T11:51:07Z"
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-j2vcs
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.20.175.120
  hostIPs:
  - ip: 172.20.175.120
  phase: Running
  podIP: 172.20.168.16
  podIPs:
  - ip: 172.20.168.16
  qosClass: Burstable
  startTime: "2025-10-17T11:51:06Z"
