apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-10-21T15:39:28Z"
  generateName: kube-proxy-
  labels:
    controller-revision-hash: 7c9cdc6f4d
    k8s-app: kube-proxy
    pod-template-generation: "2"
  name: kube-proxy-4p6zn
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-proxy
    uid: 5bdf44c1-3274-4849-9282-9cd568824497
  resourceVersion: "1081"
  uid: d84c26d9-f574-450a-a99e-5497611a42b0
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-172-20-167-18.eu-west-2.compute.internal
  containers:
  - command:
    - kube-proxy
    - --v=2
    - --config=/var/lib/kube-proxy-config/config
    - --hostname-override=$(NODE_NAME)
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy:v1.31.10-minimal-eksbuild.2
    imagePullPolicy: IfNotPresent
    name: kube-proxy
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
    - mountPath: /var/lib/kube-proxy/
      name: kubeconfig
    - mountPath: /var/lib/kube-proxy-config/
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zgvz9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: ip-172-20-167-18.eu-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: kube-proxy
  serviceAccountName: kube-proxy
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - configMap:
      defaultMode: 420
      name: kube-proxy
    name: kubeconfig
  - configMap:
      defaultMode: 420
      name: kube-proxy-config
    name: config
  - name: kube-api-access-zgvz9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-10-21T15:39:32Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-21T15:39:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-10-21T15:39:32Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-10-21T15:39:32Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-21T15:39:28Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://60a081ec05cf6a1860f876c1202e51e8c61ae4143cb76ba88bf819b76ffff9fc
    image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy:v1.31.10-minimal-eksbuild.2
    imageID: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy@sha256:aeb4d619b1faf5857f7539807679ba222720fedabcb9dae542addebd399e9e4b
    lastState: {}
    name: kube-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-10-21T15:39:32Z"
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/lib/kube-proxy/
      name: kubeconfig
    - mountPath: /var/lib/kube-proxy-config/
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zgvz9
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.20.167.18
  hostIPs:
  - ip: 172.20.167.18
  phase: Running
  podIP: 172.20.167.18
  podIPs:
  - ip: 172.20.167.18
  qosClass: Burstable
  startTime: "2025-10-21T15:39:28Z"
