apiVersion: v1
kind: Pod
metadata:
  annotations:
    github_teams: all-org-members
  creationTimestamp: "2025-10-22T15:50:58Z"
  generateName: kube-proxy-
  labels:
    controller-revision-hash: 7cc9b95d49
    k8s-app: kube-proxy
    pod-template-generation: "3"
  name: kube-proxy-2859n
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-proxy
    uid: 5bdf44c1-3274-4849-9282-9cd568824497
  resourceVersion: "494585"
  uid: 1773883e-9ccf-46a2-9f46-302f1e504e25
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-172-20-140-15.eu-west-2.compute.internal
  containers:
  - command:
    - kube-proxy
    - --v=2
    - --config=/var/lib/kube-proxy-config/config
    - --hostname-override=$(NODE_NAME)
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy:v1.31.10-minimal-eksbuild.12
    imagePullPolicy: IfNotPresent
    name: kube-proxy
    resources:
      requests:
        cpu: 100m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
    - mountPath: /var/lib/kube-proxy/
      name: kubeconfig
    - mountPath: /var/lib/kube-proxy-config/
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vb2mn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: ip-172-20-140-15.eu-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: kube-proxy
  serviceAccountName: kube-proxy
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - configMap:
      defaultMode: 420
      name: kube-proxy
    name: kubeconfig
  - configMap:
      defaultMode: 420
      name: kube-proxy-config
    name: config
  - name: kube-api-access-vb2mn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-10-22T15:51:02Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-10-22T15:50:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-10-22T15:51:02Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-10-22T15:51:02Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-10-22T15:50:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://8f4857fd6fa1ac3000ac0715c404626b1280e504565835e4c8ae7815ebdf0bbb
    image: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy:v1.31.10-minimal-eksbuild.12
    imageID: 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/kube-proxy@sha256:0de23c05f65fdbc916d05d77a87a3dfe1084cd53af9e0832de70ef39bf7a0cee
    lastState: {}
    name: kube-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-10-22T15:51:02Z"
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/lib/kube-proxy/
      name: kubeconfig
    - mountPath: /var/lib/kube-proxy-config/
      name: config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vb2mn
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.20.140.15
  hostIPs:
  - ip: 172.20.140.15
  phase: Running
  podIP: 172.20.140.15
  podIPs:
  - ip: 172.20.140.15
  qosClass: Burstable
  startTime: "2025-10-22T15:50:58Z"
