apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kiam-server
  namespace: kiam
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: kiam
      component: server-metrics
  namespaceSelector:
    matchNames:
      - kiam
  endpoints:
    - port: metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kiam-agent
  namespace: kiam
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: kiam
      component: agent-metrics
  namespaceSelector:
    matchNames:
      - kiam
  endpoints:
    - port: metrics
      interval: 30s
