apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default-template
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-template
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 10000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default-template
spec:
  role: "KarpenterNodeRole-cp-2107-0807" # Replace with your IAM role
  amiFamily: AL2
  amiSelectorTerms:
    - alias: "al2@latest"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cp-2107-0807" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cp-2107-0807" # replace with your cluster name
