on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  reject-malformed-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: ministryofjustice/github-actions/malformed-yaml@v17.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
