on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  reject-malformed-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: ministryofjustice/github-actions/malformed-yaml@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
