on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  reject-malformed-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
      - uses: ministryofjustice/github-actions/malformed-yaml@e09bca275bee78cbffa884b077b741609f22b5b5 #v18.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
