name: terraform-tools

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
      
      - name: List of changed files
        run: |
          mkdir -p .trivy
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            cp -r $file .trivy | true
          done
          ls .trivy -latr

      - uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          scan-ref: '.trivy'
          trivy-config: './config/trivy.yaml'
          
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.44.1
      - run: find . -type f -name "*.tfvars" -delete # remove terraform variable files before linting
      - run: tflint --version
      - run: tflint --init
      - run: tflint -f compact --recursive -c $(realpath .tflint.hcl)
  tfsec:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          tfsec_args: --force-all-dirs --soft-fail -m=CRITICAL --no-module-downloads --exclude-path=terraform/aws-accounts/cloud-platform-ephemeral-test --exclude-path=terraform/aws-accounts/cloud-platform-dsd --exclude-path=terraform/aws-accounts/cloud-platform-aws/vpc/kops --exclude-path=terraform/modules
          sarif_file: tfsec.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
